---
apiVersion: v1
kind: Namespace
metadata:
  name: super-simple-k8s-app-prod
spec:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: super-simple-k8s-app
  name: super-simple-k8s-app
  namespace: super-simple-k8s-app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super-simple-k8s-app
  template:
    metadata:
      labels:
        app: super-simple-k8s-app
        short: sska
      namespace: super-simple-k8s-app-prod
    spec:
      containers:
      - image: docker.io/freedomben/super-simple-k8s-app:latest
        name: super-simple-k8s-app
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "5Mi"
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "connect-video-processor"
        effect: "NoSchedule"
      nodeSelector:
        doks.digitalocean.com/node-pool: cvp-pool
