---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: super-simple-k8s-app
  name: super-simple-k8s-app
  namespace: super-simple-k8s-app-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: super-simple-k8s-app
  template:
    metadata:
      labels:
        app: super-simple-k8s-app
      namespace: super-simple-k8s-app-prod
    spec:
      containers:
      - image: docker.io/freedomben/super-simple-k8s-app:latest
        name: super-simple-k8s-app
        imagePullPolicy: Always
